name: sign
description: Basic state management base for dart. Sign inspired QT framework signal-slot architecture.
version: 0.0.2
repository: "https://github.com/Mehmetyaz/sign"
homepage: "https://github.com/Mehmetyaz/sign"



environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
